name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-content:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Lexikon
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.1
      - name: Build content
        run: ./run.sh content_build
      - name: Upload built files
        uses: actions/upload-artifact@v4
        with:
          name: content
          path: build/content/
      - name: Upload quartz overrides
        uses: actions/upload-artifact@v4
        with:
          name: quartz
          path: quartz/

  build-page:
    needs: build-content
    runs-on: ubuntu-22.04
    steps:
      - name: Check out Quartz
        uses: actions/checkout@v4
        with:
          repository: 'jackyzha0/quartz'
          ref: v4.4.0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Download Quartz overrides
        uses: actions/download-artifact@v4
        with:
          name: quartz
          path: ./
      - name: Install Dependencies
        run: npm ci
      - name: Download built files
        uses: actions/download-artifact@v4
        with:
          name: content
          path: content/
      - name: Build Quartz
        run: npx quartz build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    needs: build-page
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
